### ISSUE TITLE
calibration by TDOA loc

### ISSUE THREAD

**Issue by j054n** [StevenJL/tdoa_localization#4]
Hi,
In a similar but inverse system, I have 4 emitter beacons and a set of calibration points (3/4/5?) in which I obtain 3 TDOAs by point, and I want to obtain the positions of beacons.
Could I apply your algorithm in this way?
Thanks in advance.

**Comment by StevenJL** [comment]
If the the beacons are emitting sound (not light) and you have at least 5 receivers, it should work.

**Comment by j054n** [comment]
Thank you, I have an only mobile receiver which takes measurements in calibration points (so 5 points), I think it's a similar situation, but it is very difficult for me to write these equations in reverse mode.
Could you help me with this?

**Comment by j054n** [comment]
it does not matter, I already got it done, thanks anyway
